; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "Launcher Agent"
!define PRODUCT_VERSION "1.0.0"
!define PRODUCT_PUBLISHER "Jm's Corp"
!define PRODUCT_WEB_SITE "http://www.namejm.kr/"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\Launcher Agent.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Welcome page
; !insertmacro MUI_PAGE_WELCOME
; License page
; !insertmacro MUI_PAGE_LICENSE "..\..\..\path\to\licence\YourSoftwareLicence.txt"
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
; !define MUI_FINISHPAGE_RUN "$INSTDIR\Launcher Agent.exe"
; !insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "Korean"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "Launcher_Agent_Setup.exe"
InstallDir "$PROGRAMFILES\Launcher Agent"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite try
  File "..\Launcher Agent\bin\Release\Launcher Agent.exe"
  File "..\Launcher Agent\bin\Release\Newtonsoft.Json.dll"
  File "..\Launcher Agent\bin\Release\NLog.dll"
  File "..\Launcher Agent\bin\Release\System.Threading.Tasks.Dataflow.dll"
  File "..\Launcher Agent\bin\Release\vtortola.WebSockets.Deflate.dll"
  File "..\Launcher Agent\bin\Release\vtortola.WebSockets.dll"
  File "..\Launcher Agent\bin\Release\vtortola.WebSockets.Rfc6455.dll"
  Detailprint "Installing Service"
  nsExec::Exec 'sc create "Launcher_Agent" binpath= "$INSTDIR\Launcher Agent.exe"'
  nsExec::Exec 'sc config Launcher_Agent start= auto'
  nsExec::Exec 'sc start Launcher_Agent'

; sc create "Launcher_Agent" binpath= "$INSTDIR\Launcher Agent.exe"
; sc config Launcher_Agent start= auto
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\Launcher Agent.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\Launcher Agent.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name)��(��) ������ ���ŵǾ����ϴ�."
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Do you want to remove it" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\vtortola.WebSockets.Rfc6455.dll"
  Delete "$INSTDIR\vtortola.WebSockets.dll"
  Delete "$INSTDIR\vtortola.WebSockets.Deflate.dll"
  Delete "$INSTDIR\System.Threading.Tasks.Dataflow.dll"
  Delete "$INSTDIR\NLog.dll"
  Delete "$INSTDIR\Newtonsoft.Json.dll"
  Delete "$INSTDIR\Launcher Agent.exe"

  RMDir "$INSTDIR"

  Detailprint "Stop Service"
  nsExec::Exec 'sc stop "Launcher_Agent"'

  Detailprint "Installing Service"
  nsExec::Exec 'sc delete "Launcher_Agent"'

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd